
# Datasource (H2 in-memory dev)
## Usar H2 em memória para desenvolvimento rápido
spring.datasource.url=jdbc:h2:mem:hoteldamaria;DB_CLOSE_DELAY=-1;MODE=MYSQL
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# Mostrar SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Criar as tabelas automaticamente no H2 em memória
# Usamos create-drop para garantir o schema durante a execução (em memória)
spring.jpa.hibernate.ddl-auto=create-drop

# Corrige a ordem: executa data.sql DEPOIS que as tabelas sao criadas
spring.jpa.defer-datasource-initialization=true

# Configuracao do console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
