# Datasource (H2 in-memory dev)
spring.datasource.url=jdbc:h2:mem:hoteldamaria;DB_CLOSE_DELAY=-1;MODE=MYSQL
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# Mostrar SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Usar JPA/Hibernate para gerar DDL e também exportar para arquivo (JPA standard properties)
spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=target/schema.sql
spring.jpa.properties.javax.persistence.schema-generation.scripts.drop-target=target/drop.sql
spring.jpa.properties.javax.persistence.schema-generation.create-source=metadata
spring.jpa.properties.javax.persistence.schema-generation.drop-source=metadata

# hibernate DDL - necessário para criar as tabelas na sessão
spring.jpa.hibernate.ddl-auto=create

# Configuração do console H2 (útil p/ debugar)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
